/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "ambilight.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Message, Message, 2)


PB_BIND(Message_Config, Message_Config, AUTO)


PB_BIND(Message_Data, Message_Data, 2)






